### ISSUE TITLE
Enhance "split dictionary style data" command to take more than one column into account

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#1908]
*Issue migrated from trac ticket # 1908*

**milestone:** HeuristicLab.DataImporter 1.0.1 | **component:** DataImporter | **priority:** lowest

#### 2012-08-01 13:03:26: @mkommend created the issue

___
> Currently it is only possible to split one column according to a given identity and grouping column. This should be extended to work with selected multiple columns

**Comment by gkronber** [comment]
DataImporter is not part of HL
