### ISSUE TITLE
All AddColumn commands should take into account if any columns are selected

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#1956]
*Issue migrated from trac ticket # 1956*

**milestone:** HeuristicLab.DataImporter 1.0.1 | **component:** DataImporter | **priority:** lowest

#### 2012-09-21 10:12:02: @mkommend created the issue

___
> Currently the `AddDoubleCommand` respects if columns and inserts the new column next to the selected column. However, this behavior is not implemented in all `AddColumn` commands and should be unified.

**Comment by gkronber** [comment]
DataImporter is not part of HeuristicLab
