### ISSUE TITLE
Functionality to dynamically define symbols and semantics for GP problems

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2026]
*Issue migrated from trac ticket # 2026*

**milestone:** HeuristicLab 4.x Backlog | **component:** Encodings.SymbolicExpressionTreeEncoding | **priority:** medium

#### 2013-03-31 15:17:04: @gkronber created the issue

___
> Here we track developments of the GPDL language including the compiler frontend and different backends. GPDL and a prototype compiler for HeuristicLab was first presented at GECCO'13 in Amsterdam http://dev.heuristiclab.com/GPDL

**Comment by gkronber** [comment]
Code still lives in svn branch.
