### ISSUE TITLE
Improve serialization and deserialization of Dataset

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2659]
*Issue migrated from trac ticket # 2659*

**milestone:** HeuristicLab 3.3.x Backlog | **component:** Problems.DataAnalysis | **priority:** medium

#### 2016-08-17 13:14:02: @gkronber created the issue

___
> It seems persistence of the individual columns (IList) is very slow.
> It might be useful to use RLE or other forms of compression for some of the columns.

**Comment by gkronber** [comment]
We use HEAL.Attic now which is much faster.
