### ISSUE TITLE
Generate random regression benchmark instances

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2704]
*Issue migrated from trac ticket # 2704*

**milestone:** HeuristicLab 3.3.17 | **component:** Problems.DataAnalysis.Symbolic | **priority:** medium

#### 2016-11-23 14:50:21: @foolnotion created the issue

___
> The ability to randomly generate symbolic regression benchmarks according to user-defined rules would be useful for testing new algorithms and for the development of knowledge networks. 
> 
> A previous effort exists (ticket #2083) for generating data according to user specified formulas. This ticket has a different scope as the focus is shifted towards generation of random instances based on user-defined templates. 
> 
>

**Comment by gkronber** [comment]
Obsolete. Branch was not merged from svn
