### ISSUE TITLE
Bayesian Nonlinear Regression

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2893]
*Issue migrated from trac ticket # 2893*

**milestone:** HeuristicLab 4.x Backlog | **component:** Algorithms.DataAnalysis | **priority:** low

#### 2018-02-09 16:11:40: @gkronber created the issue

___
> Currently, HL supports non-linear regression which uses the LM algorithm to fit parameters to a given non-linear model. The trained model can be used to calculate a predicted value for new inputs. 
> 
> This is closely related to constants optimization in symbolic regression models, as we are using the same implementation for both.
> 
> It would be interesting to provide a feature for 'Bayesian non-linear regression'. The algorithm should determine a posterior distribution for the parameters given the data. The trained model can then be used to calculate a predictive distribution for new inputs. 
> 
> It is often not possible to determine the posterior distribution analytically (depends on the structure of the model). An possible solution might be to use MCMC sampling to to estimate the posterior distribution. The samples from the posterior can than be used to calculate an estimated predictive distribution for each input. 
> 
> Hamiltonian Monte Carlo seems to work well for similar tasks (see e.g. https://arxiv.org/pdf/1206.1901.pdf and http://mc-stan.org/)

**Comment by gkronber** [comment]
Exploratory branch was not merged. Closing for now. Create a new ticket when this pops up again.
