### ISSUE TITLE
Description of GBM algorithm is wrong

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2899]
*Issue migrated from trac ticket # 2899*

**milestone:** HeuristicLab 4.0 | **component:** Algorithms.DataAnalysis | **priority:** medium

#### 2018-02-13 21:21:58: @gkronber created the issue

___
> Mention of MCTS SymReg should be removed.
> 
> The namespace should also be fixed.

**Comment by gkronber** [comment]
Already solved.
