### ISSUE TITLE
Support for AutoDiff-based optimization of coefficients for symbolic regression models with auto-regressive variables

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2925]
*Issue migrated from trac ticket # 2925*

**milestone:** HeuristicLab 4.x Backlog | **component:** Problems.DataAnalysis.Symbolic | **priority:** medium

#### 2018-06-18 08:24:36: @gkronber created the issue

___
> We aim to model dynamical systems using a set of differential equations for observed variables of the system. The proposed approach is to simulate the system forward in time using numerical integration (e.g. Runge-Kutta). If we want to combine this with our gradient-based optimization of coefficients then it is necessary to calculate gradients using AutoDiff over all steps of the numeric integration. For this it is probably necessary to extend the class for optimization of coefficients (aka ConstantsOptimizer) and to provide a symbol for auto-regressive variables where it is possible to set a gradient value.
> 
> E.g. for a uni-variate model:
> y'(t) = a * y(t)
> 
> we have:
> 0. y'(0) = a y(0)
> 0. y'(1) # a y(1)a (y(0) + a y'(0)) = a y(0) + a²y'(0)
> using a naive integration step
> 
> and:
>  dy'(0)/da = y(0)
> which we need to calculate the dy'(1) / da
> 
> i.e.
>  dy'(1)/da # y(0) + 2 a dy'(0)/day(0) + 2 a y(0)
> 
> and so on for each time step.

**Comment by gkronber** [comment]
Code now lives in a separate (private) repository.
