### ISSUE TITLE
AutoDiff support for interval calculation

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#2994]
*Issue migrated from trac ticket # 2994*

**milestone:** HeuristicLab 3.3.x Backlog | **component:** Problems.DataAnalysis.Symbolic | **priority:** medium

#### 2019-03-12 12:00:57: @gkronber created the issue

___
> Support for interval arithmetic has been added in #2966.
> 
> This allows us to calculate an approximation for the value range when expressions are evaluated. We want to consider the output interval also within optimization of numeric parameters of models. Therefore, we need to be able to calculate gradients for intervals.
> 
> Changes in this ticket include our own implementation of automatic differentiation (AutoDiff) for symbolic expressions with support for the BatchInterpreter and the IntervalInterpreter.
> 
> (Depends on #2966, #2958, #2435 (alglib 3.15.0), #2971)

**Comment by gkronber** [comment]
Exploratory code in svn branch was not imported to git. 
The used a single interpreter class for evaluation of trees for any "AlgebraicType" which included doubles, vectors of doubles, intervals, ....
