### ISSUE TITLE
Constraints and Splitting for Interval Arithmetic

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#3073]
*Issue migrated from trac ticket # 3073*

**milestone:** HeuristicLab 3.3.17 | **component:** Problems.DataAnalysis | **priority:** medium

#### 2020-06-08 05:48:09: @chrishaider created the issue

___
> Extend the current interval arithmetic
> 
> - Add shape constraints to define constraints over the model and its partial derivatives
> - Add splitting for intervals to reduce the overestimation of boundaries

**Comment by gkronber** [comment]
All changes of this ticket are already in the main branch.
