### ISSUE TITLE
Integrate Ceres with the native interpreter and extend features

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#3087]
*Issue migrated from trac ticket # 3087*

**milestone:** HeuristicLab 3.3.x Backlog | **component:** Problems.DataAnalysis.Symbolic.Regression | **priority:** medium

#### 2020-11-09 15:24:02: @foolnotion created the issue

___
> We can use Eigen/Ceres inside the native interpreter and be able to:
> 
> - use Eigen for evaluation
> - optimize model coefficients using nonlinear least squares
> - pass solver options to Ceres
> - get a report from the solver (successful steps, error, etc)

**Comment by gkronber** [comment]
@foolnotion how shall we proceed with this branch? The main issue has been solved (native parameter optimizer in HL). Do we need to merge the changes to TriangularMatrix?

**Comment by foolnotion** [comment]
#3100 is probably still relevant but should be addressed separately. I suggest we close this since as you mentioned the main issue has been solved. New features for the native parameter optimize can be added with new issues/PRs.
