### ISSUE TITLE
Partial dependence plot for ensemble solutions

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#3096]
*Issue migrated from trac ticket # 3096*

**component:** Problems.DataAnalysis.Views | **priority:** medium

#### 2021-01-06 10:47:27: @gkronber created the issue

___
> A specific view for ensemble solutions should show a partial dependence plot with curves for all solutions in the ensemble.

**Comment by gkronber** [comment]
A runcollection view already provides similar functionality
