### ISSUE TITLE
Implementation of Analytic Continued Fractions for Regression

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#3106]
*Issue migrated from trac ticket # 3106*

**milestone:** HeuristicLab 3.3.x Backlog | **component:** Algorithms.DataAnalysis | **priority:** medium

#### 2021-02-25 15:37:17: @gkronber created the issue

___
> See https://arxiv.org/abs/2001.00624
> 
> The implementation is done within a Master's thesis

**Comment by gkronber** [comment]
Code is managed in a separate git repo
