### ISSUE TITLE
Overflow in calculation of axes range in partial dependence plot

### ISSUE THREAD

**Issue by HeuristicLab-Trac-Bot** [heal-research/HeuristicLab#3112]
*Issue migrated from trac ticket # 3112*

**milestone:** HeuristicLab 3.3.17 | **component:** Visualization.ChartControlsExtensions | **priority:** medium

#### 2021-03-09 07:57:32: @gkronber created the issue

___
> Models which produce a large range of outputs i.e. in the range 0 .. 10^10^ lead to an overflow in CalculateAxisInterval in particular in methods RoundDown() and RoundUp(). Both methods cast to an int which limits the maximum range to the 2^31^. The cast to integer is however not required as the code should be fine with floating point arithmetic.

**Comment by gkronber** [comment]
This has been fixed directly in main.
